name: Build Boards

on:
  push:
    branches:
      - main
      - ci/*
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  prepare:
    name: Determine variants to build
    runs-on: ubuntu-latest
    outputs:
      variants: ${{ steps.select.outputs.variants }}
    steps:
      - id: select
        name: Set single board variant
        shell: bash
        run: |
          echo 'variants=[{"board":"bread-compact-wifi-s3cam","name":"bread-compact-wifi-s3cam","full_name":"bread-compact-wifi-s3cam"}]' >> "$GITHUB_OUTPUT"

  build:
    name: Build ${{ matrix.full_name }}
    needs: prepare
    if: ${{ needs.prepare.outputs.variants != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.variants) }}
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v5.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Clean build environment & execute build
        shell: bash
        run: |
          source $IDF_PATH/export.sh
          rm -rf build dependencies.lock managed_components
          python scripts/build.py ${{ matrix.board }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xiaozhi_${{ matrix.full_name }}_${{ github.sha }}
          path: build/merged-binary.bin
          if-no-files-found: error